name: Deploy react project
on: [push, workflow_dispatch]
jobs: 
  test:
    runs-on: macos-latest
    defaults:
      run: 
        working-directory: react-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy:
    needs: test
    runs-on: macos-latest
    defaults:
      run: 
        working-directory: react-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying"
