name: Deployment exercise 1
on:
  push:
   paths: 
    - deployment-exercise-1/**
  workflow_dispatch:
jobs:
  lint:
    defaults:
      run: 
        working-directory: deployment-exercise-1
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
        
  test:
    defaults:
      run: 
        working-directory: deployment-exercise-1
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  build:
    defaults:
      run: 
        working-directory: deployment-exercise-1
    needs: test
    runs-on: macos-latest
    outputs: 
      script-file: ${{ steps.publish.output.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: |
          npm run build
          ls
      - name: Publish js file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: dist-files
          path: deployment-exercise-1/dist
  deploy:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Display files
        run: ls -l
      - name: output file name
        run: echo "${{ needs.build.output.script-file }}"
      - name: Deploy
        run: echo "Deploying..."

