name: Test react project
on: push
jobs: 
  test-react-project:
    runs-on: macos-latest
    defaults:
      run: 
        working_directory: react-project
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node js
        uses: actions/setup-node@v3
          with:
            node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test