name: Test and deploy practice project
on: push
jobs:
  test:
    defaults:
      run: 
        working-directory: react-project-practice
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
      - name: Test
        run: npm test
  deploy:
    defaults:
      run: 
        working-directory: react-project-practice
    needs: test
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
